apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: nginx
spec:
  containers:
    - name: nginx-container
      image: registry.hub.docker.com/library/nginx
      ports:
        - containerPort: 80
